version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./dbdata:/var/lib/postgresql/dados
      - ./dados/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - 5432:5432